name: Lint for Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    if: ${{ !contains(github.head_ref, 'develop') && !contains(github.head_ref, 'main') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    name: Linting
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Node Modules
        run: npm ci

      - name: Linting
        run: pnpm run lint

      - name: Build App And Storybook as Testing
        run: |
          pnpm run build
          pnpm run build-storybook
